### ISSUE TITLE
Idea - Do something similar for android

### ISSUE THREAD

**Issue by morpheasgr** [itsToggle/rclone_RD#1]
Greetings :) so happy to see people creating stuff for RD. Since the service devs seem kinda focused on maintaining lately, still no feature such as WebDAV/SFTP or any kind of integration besides their api.

I was wondering whether one could do something similar for Android by forking this rclone client https://github.com/x0b/rcx

Sure, you need root to natively mount remote filesystems systemwide (afaik) but you can still make them accessible for other apps via the SAF (storage access framework). The dev of this android client is kinda inactive for the last year but there's a pull request regarding SAF. Maybe there is also an active fork someplace, or there's a better open-source alternative that can be forked to use for such a purpose.

Either way that would be a very nifty feature to have. :) Recently switched debrid providers mainly for the reason that RD offers no filesystem integration and also because there is no tool for windows to associate torrents and magnets and offer basic cloud management outside of the browser on Windows. Been actually using Windows 11's WSA (android subsystem) to use an Android app (Unchained) for that task.

**Comment by itsToggle** [comment]
Thats a great idea! I also switched to premiumize a while back, but using their cloud for storage is just too damn expensive (since both traffic and storage count towards your 1TB/month.
I don't have any android programming knowlegde, so its best someone else look into this.
For now, you could mount RD on Windows using this Fork, share the drive on your local network and then mount it using some android app. You can also start a realdebrid webdav or dlna server using this rclone fork.

**Comment by itsToggle** [comment]
Just had a closer look at the repo, this might be easier than I thought. You just need to provide my rclone fork instead of the official rclone fork as the repository that RCX utilizes. Perhaps you could even replace the files that I changed in one of the apk releases. If you find an active rcx fork with the features you like, let me know.

**Comment by itsToggle** [comment]
If you are still interested, Ive released an android version. 
This version is based the latest release from the rcx github. Ive simply replaced the 'librclone.so' file inside the apk with a compiled version of my rclone fork. To be able to install the apk, the app needed to be signed again which i have done with an apk-signer app from the playstore. 
To add realdebrid as a remote, simply setup a realdebrid remote on your PC and copy the `rclone.conf` file (`C:\Users\BigSchlong\.config\rclone`) to your android device. Inside the RCX App you can now load your rclone config file. Youre done, you can mount realdebrid on your android device :)
![Screenshot_20220609-154243_RCX - Rclone for Android](https://user-images.githubusercontent.com/71379623/172864531-4e6c07ce-7621-403d-b162-c01aaf115a71.jpg)
