### ISSUE TITLE
ERROR : IO error: couldn't list files: 503 Service Unavailable (503):

### ISSUE THREAD

**Issue by piratsch** [itsToggle/rclone_RD#10]
When the fork is trying to create an unrestricted link, I often get the following error message: 

```
ERROR : IO error: couldn't list files: 503 Service Unavailable (503): {
	"error": "hoster_unavailable",
	"error_code": 19
}
```
The generation of other links works fine however.

**Comment by itsToggle** [comment]
This is related to issue #6. Sometimes when adding a torrent, the generated restricted links that realdebrid produces are broken. This can sadly only be fixed by re-adding the torrent, which is not something that I can integrate into rclone (for reasons provided in issue #6).
Have you noticed a pattern of the torrents this happens to? I've only ever had this issue once.

**Comment by ppogorze** [comment]
@itsToggle what about AllDebrid? Their webdav implementation is better?

**Comment by itsToggle** [comment]
will close this as this is continued in #14
