### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by magnu5** [itsToggle/rclone_RD#24]
Any chance for a dockerized version of this?

**Comment by itsToggle** [comment]
You would need to create a container that contains both Plex and rclone_rd, otherwise plex wont be able to see the mounted files. At least as far as Im understanding it - there are existing containers out there for Plex and the official rclone software. 
Because I have no idea how I would put plex inside a container, and other people might prefer a different PMS, there is no plans for this at the moment. Do tell me if you find out something else though.

**Comment by magnu5** [comment]
there is no need for including plex as you would mount volumes for the storage needed as usual using 
`-v /localpath:/dockerpath `
and then just map those folders in plex/jellyfin as you would normally do.
```
-v /where/to/store/config:/config
-v /path/to/rd-files/:/real-debrid
-v /path/to/other-debrid:/other-debrid
```
but no worries, someday maybe.

**Comment by itsToggle** [comment]
Thanks! That could be a way of creating this as a dockerized version then. Here's the way the official rclone software connects to docker: https://rclone.org/docker/ - theyve created some soft of plugin for docker. I'll play around with that and see if I can create my fork as a plugin aswell

**Comment by carloss66** [comment]
A Docker version of rclone_rd would be great. Thanks for your work.

**Comment by itsToggle** [comment]
docker version is live on dockerhub! 

`docker plugin install itstoggle/docker-volume-rclone_rd`

You can check out the usage on https://rclone.org/docker/ :)
